### ISSUE TITLE
Header + delete character

### ISSUE THREAD

**Issue by andreacagnina** [andreacagnina/GDR#6]
aggiungi al logo dell'header la rotta per la home page e ai vari nav link la classe dinamica in base se la rotta è arriva, modificando il colore del link stesso. {{route:currentRouteName() }}

Su scss puoi riprendere il colore del font utilizzando la variabile $color_text

finita la navbar, puoi fare il necessario per cancellare un personaggio dalla lista

**Comment by Francesco-Alquati** [comment]
Fatto tutto!
